steps:
  # Paso 1: Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservices-test-454912/test/products-ms-prod",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]


  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservices-test-454912/test/products-ms-prod",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/microservices-test-454912/serviceAccounts/239268984077-compute@developer.gserviceaccount.com"
